name: toddle
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  awesome_dialog: ^3.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  intl: ^0.17.0
  date_picker_timeline: ^1.2.3
  sqflite: ^2.2.6
  flutter_staggered_animations: ^1.1.1
  flutter_launcher_icons: ^0.12.0
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/man.png

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
