name: toddle
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  awesome_dialog: ^3.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  intl: ^0.17.0
  date_picker_timeline: ^1.2.3
  sqflite: ^2.2.6
  flutter_staggered_animations: ^1.1.1
  flutter_launcher_icons: ^0.12.0
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  flutter_native_splash: ^2.2.19
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.1.1+1
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  # color: "#F5F7ED"
  # image: images/for_splash.png
  # branding: images/for_splash.png
  color_dark: "#303030"
  # image_dark: images/for_splash.png
  # branding_dark: images/for_splash.png

  android_12:
    # image: images/for_splash.png
    icon_background_color: "#F5F7ED"
    # image_dark: images/for_splash.png
    icon_background_color_dark: "#303030"

  web: false

flutter:
  uses-material-design: true
  assets:
    - images/man.png
    - images/for_splash.png
    - images/splash/bigBlob.png
    - images/splash/dots1.png
    - images/splash/lines.png
    - images/splash/smolines.png

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/toddle_icon.png"
